language: node_js
before_script:
  - unset FSD_COVERAGE
  - gulp
#  - gulp instrument
node_js:
 - "6"
 - "node"
# - "4"   does not support sourcemaps
after_script:
  - npm run instrument
  - npm run testcov2
  - npm run testcov

